######################################################################
# Automatically generated by qmake (2.01a) ? 11? 29 15:59:50 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
